### ISSUE TITLE
WundergroundWeather: Cannot auto-convert value

### ISSUE THREAD

**Issue by ssifue** [symcon/SymconMisc#4]
In meinem Log findet sich bei Abrufen des aktuellen Wetters folgende Warnung. Eingestellter Standort ist EDDN.

06.02.2017 11:49:20 | ScriptEngine | Result for Event 33378

<b>Warning</b>:  Cannot auto-convert value for parameter VariableValue in <b>/var/lib/symcon/modules/SymconMisc/WundergroundWeather/module.php</b> on line <b>138</b><br />
<br />
<b>Warning</b>:  Cannot auto-convert value for parameter VariableValue in <b>/var/lib/symcon/modules/SymconMisc/WundergroundWeather/module.php</b> on line <b>145</b><br />

**Comment by paresy** [comment]
Ist mit https://github.com/symcon/SymconMisc/commit/42db69b63e1f36728b955295791b5aee4ebfd5ad gelöst.
